### ISSUE TITLE
add role="presentation" to list items in menu on "After" page

### ISSUE THREAD

**Issue by robfentress** [terrill/AU#3]
For the menu on the "After" page, I believe you must add `role="presentation"` to the `<li>` tags, since you have changed the role of the parent `<ul>` tag to `menubar`.  Basically, elements with the role, [listitem](https://www.w3.org/TR/wai-aria-1.1/#listitem), must have a parent with a role of [list](https://www.w3.org/TR/wai-aria-1.1/#list-0) or, maybe, [group](https://www.w3.org/TR/wai-aria-1.1/#group) (not sure about the group role--the spec seems unclear on this to me).

**Comment by terrill** [comment]
This has been fixed in c907c966326f6d34e6758a74add66b9ab08c9f04
